### ISSUE TITLE
Specify version for the datadog-ci installation

### ISSUE THREAD

**Issue by bcaurel** [DataDog/junit-upload-github-action#13]
Hi :)

## Context

- The datadog-ci was released with errors (2.16.0 and fixed in [2.16.1](https://github.com/DataDog/datadog-ci/pull/951))
- The latest datadog-ci version is installed in the junit-uplaod-github-action [here](https://github.com/DataDog/junit-upload-github-action/blob/main/action.yaml#L49) 

## Problem
Even if we don't upgrade the github action on our side we pull the error because of the install of the latest version of datadog-ci

## Proposal
Specify the version of datadog-ci in the installation and release a new version the junit-uplaod-github-action for each new release of datadog-ci

**Comment by juan-fernandez** [comment]
hey @bcaurel ! I think this makes total sense. I've implemented it in https://github.com/DataDog/junit-upload-github-action/pull/18. Sorry for the long delay to response 😅
