### ISSUE TITLE
Reports are duplicated in Datadog CI Visibility

### ISSUE THREAD

**Issue by smolse** [DataDog/junit-upload-github-action#7]
Version: 1.1.1

After using this action in a GitHub Actions workflow to upload JUnit test reports to Datadog I noticed that test runs in Datadog CI Visibility are duplicated. Based on the workflow logs, it looks like the upload steps on lines [#46](https://github.com/DataDog/junit-upload-github-action/blob/main/action.yaml#L46) and [#60](https://github.com/DataDog/junit-upload-github-action/blob/main/action.yaml#L60) in the action YAML file are both always executed, even though they are supposed to be mutually exclusive. The same behavior can also be seen in the test workflow logs in this repo (`logs` is set to "true", but upload without logs still runs), e.g.: https://github.com/DataDog/junit-upload-github-action/runs/6904512151?check_suite_focus=true#step:3:56

According to https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepsif and https://docs.github.com/en/actions/learn-github-actions/expressions#about-expressions, whole `if` statement must be an expression. So, the correct way to define `if` conditionals is as following:

```
if: ${{ inputs.logs == 'true' }}
```

or simply

```
if: inputs.logs == 'true'
```

Not sure why exactly `${{ inputs.logs }} == "true"` statement doesn't work, my guess is that it's possibly treated by GitHub as a string literal because it starts with `${{`, but doesn't end with `}}`.

**Comment by cg14823** [comment]
Hi,

This is now fix I believe. Sorry I could not merge your contribution, I will explore what the permission issue is and strive to fix it.

**Comment by smolse** [comment]
Hey Carlos, no worries! Thank you for incorporating the fix and releasing new version of the action so promptly 👍
